server:
  compression:
    enabled: true
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/websocket?useSSL=false&serverTimezone=JST&useLegacyDatetimeCode=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: test
    password: password
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: JST
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    rest:
      base-path: /api
logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

