server:
  compression:
    enabled: true
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polls?useSSL=false&serverTimezone=JST&useLegacyDatetimeCode=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: test
    password: password
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: JST
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
#    org:
#      springframework: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey