server:
  compression:
    enabled: true
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/polls?useSSL=false&serverTimezone=JST&useLegacyDatetimeCode=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: test
    password: password
#    schema: src/main/resources/db/schema.sql
#    data: src/main/resources/db/db/data.sql
#    initialization-mode: always
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: JST
  jpa:
    open-in-view: true
#    show-sql: true
#    hibernate:
#      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
logging:
  level:
#    org:
#      springframework: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey