server:
  compression:
    enabled: true
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polls?useSSL=false&serverTimezone=JST&useLegacyDatetimeCode=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: callicoder
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: JST
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey