server:
  compression:
    enabled: true
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petclinic?useSSL=false&serverTimezone=JST&useLegacyDatetimeCode=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: test
    password: password
#    schema: classpath*:db/schema.sql
#    data: classpath*:db/data.sql
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: JST
  jpa:
    open-in-view: true
#    show-sql: true
#    hibernate:
#      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  messages:
    basename: messages/messages
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  profiles:
    active: production
logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE