server:
  compression:
    enabled: true
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/react-native?useSSL=false&serverTimezone=JST&useLegacyDatetimeCode=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: JST
  jpa:
    open-in-view: true
#    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    rest:
      base-path: /api
logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE